services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nginx
    networks:
      - nginx-network
    ports:
      - "8080:80"
      - "8000:443"
    # volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  nginx-network:
    driver: bridge